### ISSUE TITLE
having issue with Dockerfile

### ISSUE THREAD

**Issue by saeedullahumar** [sdhmh/restormerui-backend#1]
something is not fine in the Dockerfile plz check it out giving error of 

ERROR: failed to solve: process "/bin/sh -c . /setup/miniconda3/bin/activate &&     conda create -n app python=3.7 -y &&     conda activate app &&     conda install pytorch=1.8 torchvision torchaudio cpuonly -c pytorch -y" did not complete successfully: exit code: 1

**Comment by sdhmh** [comment]
The dockerfile needs a stable internet connection. If you are having issues while building it, try to create an EC2 Instance and build the image there.

**Comment by sdhmh** [comment]
The issue is most likely due to unstable internet connection as the same image is building inside my machine...
